### ISSUE TITLE
Reference field filter returns all when no match

### ISSUE THREAD

**Issue by mingard** [dadi/api#118]
### Expected behavior

This query should return no results as the second condition yeilds no match
```JSON
{
"toplistFeature": true, 
"publication.furl": "cool-fm"
}
```

### Actual behavior

The query returns all results

### Steps to reproduce

@jimlambie @eduardoboucas I can show you this in action

**Comment by jimlambie** [comment]
@mingard I need more information for this. A collection schema and some sample data would be useful.

**Comment by mingard** [comment]
@jimlambie I'll show you this in action today

**Comment by jimlambie** [comment]
Closing, not an issue.

The filter field name "publication" is wrong, and should be "publications". If a filter field doesn’t exist in the schema it is stripped, so you are left with `{}` which will return everything.

Please provide collection schemas when submitting issues!
