### ISSUE TITLE
Hooks cause extra revision states

### ISSUE THREAD

**Issue by mingard** [dadi/api#125]
Some hooks that prompt the re-saving of a document create a new history state. It's probably important to retain these states, but how can we flag them as 'none-user interaction' history to avoid displaying the same update twice in Publish?

Thoughts @jimlambie @eduardoboucas?

**Comment by jimlambie** [comment]
We could add a `source` property. Can you give me an example hook for testing?

**Comment by jimlambie** [comment]
Bump @mingard. Example hook?

**Comment by jimlambie** [comment]
@mingard @mingard @mingard

**Comment by mingard** [comment]
@jimlambie 

Try something like https://github.com/dadi/resources/blob/master/API/hooks/oembed-cache/oembed-cache.js where an update is made async
