### ISSUE TITLE
Token TTL index is not updated

### ISSUE THREAD

**Issue by fra967** [dadi/api#130]
### Expected behavior

When a new authentication TTL value is set in the configuration, the index that removes the token after TTL seconds is set to the configured value
### Actual behavior

At startup, an index is added on `created` field with the configured expireAfterSeconds value 
https://github.com/dadi/api/blob/77e868db2af2da6f39ca9ba9354cec4c7abbf591/dadi/lib/auth/tokenStore.js#L22
but as a previous index on the same field is present, the index is not actually created / updated

The index should be dropped before being re-created
### Steps to reproduce the problem
- start API
- check the index on tokenStore collection
- change auth.tokenTtl in config
- re-start API
- check the index on tokenStore collection
### Package details

1.11.1

**Comment by eduardoboucas** [comment]
We're no longer using indexes with `expireAfterSeconds`, so this is probably fixed. Let me know once you have a chance to test @fra967.

**Comment by fra967** [comment]
No longer using `expireAfterSeconds` indexes since which version @eduardoboucas ?

**Comment by eduardoboucas** [comment]
Since 3.0.0, so for the past 30 minutes. 😄

**Comment by eduardoboucas** [comment]
🕸 👴 

Please reopen if the problem persists.
