### ISSUE TITLE
Hook firing for Reference collection

### ISSUE THREAD

**Issue by mingard** [dadi/api#131]
### Example
1. Collection *Articles* use the `slugify` hook
2. Collection *Publications* use the `slugify` hook
3. Collection *Articles* have a _Reference_ to Collection *Publications*
4. When you save an *Article*, the `slugify` hook fires for *Publications*
5. This is saving blank *Publication* documents

Examples attached

[1ckam.zip](https://github.com/dadi/api/files/422693/1ckam.zip)

**Comment by jimlambie** [comment]
Appears to no longer be an issue in the product, rather in a client application. Closing.
