### ISSUE TITLE
Add ability to bypass hooks

### ISSUE THREAD

**Issue by eduardoboucas** [dadi/api#135]
Hooks can make debugging a bit tricky, as it becomes difficult to tell if an issues is coming from the client app, the API core or any hook in between.

I propose we look for a `bypassHooks` URL parameter that, when present, disables all hooks for the given request.

**Comment by mingard** [comment]
Useful when running batch data imports 
+ 1

**Comment by jimlambie** [comment]
@eduardoboucas this one has your name all over it...any idea when you'll be able to tackle?

**Comment by eduardoboucas** [comment]
The reason this wasn't implemented already is because there are some considerations to make about it. Whilst the ability to bypass a hook can be useful in a number of situations (such as data imports, as @mingard mentioned), it could also potentially defeat the entire purpose of a hook.

For example, imagine that someone is using hooks to build their own authentication/authorisation layer for API, where the decision to grant access to documents will be made at the hook level. If users have the ability to bypass hooks, this will be breached.

When I last discussed this with @jimlambie, I listed three possible approaches we could take:

1. We stay out of this and leave it up to each hook to decide if and how it can be bypassed (e.g. by checking for a particular URL parameter). This is our current approach.
1. We specify that hooks **can't** be bypassed by default, which can be changed by setting a flag to `true` in the hook's `options` block.
1. We specify that hooks **can** be bypassed by default, which can be changed by setting a flag to `false` in the hook's `options` block.

Thoughts?

**Comment by jimlambie** [comment]
Thanks @eduardoboucas!

I'm actually in favour of option 1 - although that makes it sound like I'm in favour of doing zero work. I feel like it's a bit cumbersome if we have a flag at the core level and also allow a hook to make a decision. I'm for leaving it up to the hook, and perhaps enforcing some kind of rules around hook coding and documentation.

**Comment by eduardoboucas** [comment]
Should we park this one, then?

**Comment by jimlambie** [comment]
Agreed, please close
