### ISSUE TITLE
Force create/ensure index on sort

### ISSUE THREAD

**Issue by mingard** [dadi/api#136]
In this example, the index keys don't contain the key for the sort param. If a sort param is set, run checkIndex on the key and create an index if missing from the result

```JSON
    "sort": "publicationDate",
    "index": {
      "enabled": true,
      "keys": {
        "_id": 1,
        "urls": 1
      }
```

Further request:

Also add the key to the collection schema

```JSON
    "sort": "publicationDate",
    "index": {
      "enabled": true,
      "keys": {
        "_id": 1,
        "publcationDate": 1,
        "urls": 1
      }
```
Even more:

When a response based on sort overflow is returned, output the existing sort keys as well as the current sortby value

### Current

```JSON
{
  "name": "MongoError",
  "$err": "Runner error: Overflow sort stage buffered data usage of 33563283 bytes exceeds internal limit of 33554432 bytes",
  "code": 17144
}
```

### Proposed

```JSON
{
  "name": "MongoError",
  "$err": "Runner error: Overflow sort stage buffered data usage of 33563283 bytes exceeds internal limit of 33554432 bytes",
  "code": 17144,
  "sort": {
    "publicationDate": 1
  },
  "indexes": {
    "urls": 1,
    "_id": 1
  }
}
```

**Comment by jimlambie** [comment]
I have a better idea. On startup, validate the collection schemas. If the specified sort field is not in the index block, warn and exit.

Thoughts, @mingard @eduardoboucas ?

**Comment by mingard** [comment]
@jimlambie yes - better/simpler approach

**Comment by eduardoboucas** [comment]
Sounds good to me!
