### ISSUE TITLE
Queries including a field of type Object, whose name starts with _, return a 500 error code

### ISSUE THREAD

**Issue by fra967** [dadi/api#140]
When including in the "fields" parameter a field whose name starts with _ and is of type object, API returns 500 instead of the document data.
This message is written in the log: "[TypeError: Cannot read property '0' of undefined]"

The query is actually executed in mongodb, and records are returned to API, but API returns a 500 error

This happens whenever the _field is present in the fields parameter, either alone or in combination with other fields. It is important that data is stored in this _field.
If there is no data, no error is returned.

The problems does not happen with a field of type string. I have not tried other types.
It does happen with type Object.

The problem does not happen if the field is renamed without the  _

### Package details
  Version:     1.12.2
  Node.JS:     4.2

**Comment by jimlambie** [comment]
@fra967 can you please specify the project, collection schema and URLs you've tested with? Feel free to attach files to this issue.

Thanks!

**Comment by jimlambie** [comment]
@fra967 @mingard the error comes from the layout hook in Radio (https://github.com/dadiplus/bauer-radio-api/blob/migration/publish/api/workspace/hooks/layout.js#L92)

I know they've been told they can't specify _layout as a field, but some better testing and error handling within custom hooks is essential. 

@eduardoboucas can we wrap the hook execution in an error handler?

Closing this issue.
