### ISSUE TITLE
Prefix internal fields

### ISSUE THREAD

**Issue by eduardoboucas** [dadi/api#141]
We could prefix with underscore (or anything) all our internal fields that get appended to documents (e.g. `createdAt`, `createdBy`, etc.). This would allow automated systems to easily strip these fields out. 

For example, API wrapper could remove internal fields from an update request and therefore avoiding a 400 response.

Also, it would be easier to create a script to export documents from DADI API to another platform, as meta fields could easily be identified and removed from the output.

This is a breaking change, so just leaving the idea here for 2.0.0.

**Comment by eduardoboucas** [comment]
Just leaving a note here that this will be a breaking change for [api-wrapper](https://github.com/dadi/api-wrapper) and [api-wrapper-core](https://github.com/dadi/api-wrapper-core) too.

**Comment by jimlambie** [comment]
As suggested by @fra967 [here](https://github.com/dadi/api/issues/300#issuecomment-313665500), an object containing all internal fields may be easier to deal with.

### Example

```
"meta": {
  "createdAt": 145482828828,
  "createdBy": publish,
}
```

**Comment by eduardoboucas** [comment]
What about `_id`? It's probably the most widely used internal field and luckily it's already prefixed. If we move all internal fields to a meta object, we'll be causing loads of problems to consumer apps. Can we justify that?

Personally I'd prefer to have the ability to configure the prefix, having `_` as the default value.

**Comment by jimlambie** [comment]
Ok, sounds fine to me. Each of the data connectors has to handle these internal fields before inserting/updating, as not all databases accept fields with an underscore for a prefix. But that's fine, as we already do that for the identifier anyway.
