### ISSUE TITLE
SSL handling

### ISSUE THREAD

**Issue by adamkdean** [dadi/api#155]
> X-Post from: https://github.com/dadi/web/issues/99

At the moment configuration appears to enable SSL as being either on or off. SSL needs to be supported in a variety of configurations:

- Just SSL
- SSL, with support for routing traffic from HTTP to HTTPS
- HTTPS alongside HTTP (either/or support)

In addition the method of recognising/enforcing an SSL request needs attention. In a load balanced setup the load balancer will usually handle SSL, piping requests as HTTP to the end instances.

**Comment by jimlambie** [comment]
Closed by 9251264ac67b02198458b0cbf2a34e0d6bfc57c7
