### ISSUE TITLE
API Async Reference document manipulation 

### ISSUE THREAD

**Issue by mingard** [dadi/api#182]
### Overview
Many of the client specific collections in Publish incorporated Reference fields to keep reusable content separated from a single parent document, either within the same collection or another.

This concept aims to shift the current asyncronous Reference document creation from Publish and move it to API.

### Why?
- Remove boilerplate Reference document generation in Publish fields
- Remove reliance on CMS to handle subdocuments
- Improve error handling (various)

#### Example POST data

```JSON
{
  "name": "Joe",
  "cars": ["587cb6aa80222c9e7266cec0", "588894d170ccb2b9c2a7c9f7"]
}
```

So lets break it down. There are two collections in play. The first is the collection we're **POST**ing to and the second is a referenced collection.

**collection.people.json**
```json
{
  "fields": {
    "name": {
      "type": "String",
      "label": "Name"
    },
    "cars": {
      "type": "Reference",
      "label": "Cars",
      "settings": {
        "collection": "classic_cars"
      }
    }
  }
}
```

**collection.classic_cars.json**
```json
{
  "fields": {
    "model": {
      "type": "String",
      "label": "Model"
    },
    "year": {
      "type": "Number",
      "label": "Year"
    }
  }
}
```

#### Current limitations

For the sample **POST** data to work, we need to have already inserted the two documents in the `cars` field. 

This reliance on an initial insert is not in itself partilarly complicated, but with a document with multiple **Reference** fields, or where there are multiple levels of nesting occure, things start to get messy.

Take an _Article_ with a **Reference** _Gallery_ where the _Gallery_ itself has a **Reference** _images_ field, to insert a new _Article_ with two new _Gallery_'s, both containing 5 new _Images_, you have 5 requests.

1. Insert Gallery Image set 1 for Gallery 1
2. Insert Gallery 1 with References to Image set 1
3. Insert Gallery Image set 2 for Gallery 2
4. Insert Gallery 2 with References to Image set 2
5. Insert Article with Reference to Gallery 1 and 2

In Publish, because you're dealing with 3 collections and 5 inserts across the internet, validation and hook failures can be hard to capture, and performance is slow.

#### Proposal

1. As we as **Arrays** and single **ObjectID** Reference fields can accept Objects
2. Object-based Reference documents are evaluated deep 
3. Object-based Reference documents with an existing `_id` field are updated in their respective collections
4. Object-based Reference documents without existing `_id` are created in their respective collections

**Comment by mingard** [comment]
@jimlambie further to our conversation, here is an example insert which requires the two collection schemas within this tickets description:

```json
{
  "name": "Joe",
  "cars": [{
    "model": "Lamborghini Diablo",
    "year": 1991
  }]
}
```
and for an update:

```json
{
  "name": "Joe",
  "cars": [{
    "_id": "587cb6aa80222c9e7266cec0",
    "model": "Lamborghini Diablo",
    "year": 1991
  }]
}
```
and for an insert with an existing document present:

```json
{
  "name": "Joe",
  "cars": [
  "587cb6aa80222c9e7266cec0",
  {
    "model": "Golf Mk2 GTI",
    "year": 1988
  }]
}
```

and for an insert with an update:

```json
{
  "name": "Joe",
  "cars": [{
    "_id": "587cb6aa80222c9e7266cec0",
    "model": "Lamborghini Diablo Coupé",
    "year": 1992
  },
  {
    "model": "Golf Mk2 GTI",
    "year": 1988
  }]
}
```

**Comment by jimlambie** [comment]
@mingard what do you hope to have returned to the calling application for each of the above scenarios?

**Comment by mingard** [comment]
Just the fully composed document.

If there are field filters in the settings block of a Reference field these should be applied

**Comment by jimlambie** [comment]
@mingard please review this feature, available in `@dadi/api@beta`
