### ISSUE TITLE
implement auth token check and manual expire

### ISSUE THREAD

**Issue by jimlambie** [dadi/api#199]
Currently in API token expiry is handled by a TTL index in mongodb. With the move to separate data modules, we need to handle this manually in API's auth layer.

**Comment by eduardoboucas** [comment]
From our Slack convo:

> random thought about the token expiration issue (it's been haunting me in my sleep): we make use of Mongo's native support for time-sensitive documents, which get automatically removed after the defined TTL. what do we do when we're using other data adapters? and what disadvantages would we have if we stopped using it for Mongo, in favour of a manual approach:
>
> - when a token is created, write it to the `clientStore` collection along with a timestamp that represents when the token will stop being valid
>
> - when an authenticated request comes in with a token, we check not only that it exists but also if the timestamp is still in the future – if not, reject the request
>
> - we can setup a cleanup process, that can run X times per day _or_ automatically kick in at periods of low traffic, that goes through records in the `clientStore` collection that have timestamps in the past and remove them
>
> the way I see it, the worst thing that can happen with this approach is that we might have a number of "dead records" in the `clientStore` collection at any given time, but this can be compensated by adjusting the cleanup interval. the biggest advantage is that we'd have a consistent approach that would work for any data adapter, without relying on their native support for TTL-based records which they may or may not support
>
> (another big advantage, of course, is that the whole process would be more transparent to us and hopefully easier to debug. we'd be able to see the actual timestamps for record removal, whereas now that is a bit opaque) (edited)

**Comment by eduardoboucas** [comment]
(The issue mentioned above refers to #75)

**Comment by jimlambie** [comment]
@eduardoboucas the API release will have to wait for this to be implemented...no pressure!

**Comment by eduardoboucas** [comment]
😬 🏃
