### ISSUE TITLE
API 2.x conventions discussion

### ISSUE THREAD

**Issue by jimlambie** [dadi/api#203]
## 👋 

Development on API 2.x is progressing reasonably quickly - we have several new datastore adapters and a unit test suite in API that is passing against most of them. There are plenty of small loose ends to tie up, but it's getting there.

With the introduction of new datastore adapters we have run into a couple of issues, specifically with CouchDB. Whatever we choose to do, there will be some kind of migration procedure to get from 1.x to 2.x. I want to open this discussion up to regular users of, and contributors to, DADI API.

The below are problems discovered when porting an API installation to CouchDB. The conventions we put in place should allow a developer to switch data adapter and make zero changes to workspace files. 

### Issues
* CouchDB _does not_ allow field names with underscores at the beginning (e.g. `_layout`). We have a ticket open to prefix internal fields in 2.x, so the decision we make here will be passed into that ticket. **Suggestion:** select a different "special field" indicator, e.g. `$layout`.
* CouchDB doesn't have a database > collection hierarchy as MongoDB does, so all collections will actually be created as databases. However CouchDB _does not_ allow camelCased database names. For example, `tokenStore` would have to become `token-store` to work in CouchDB. **Question:** is this a problem, or could we simply have the CouchDB adapter translate between these under the hood? _or_ do we define a convention for collection names that favours hyphenations over camelCase?

**Comment by josephdenne** [comment]
Translation between conventions under the hood would seem to make sense as we are likely to come up against conflicting approaches to naming conventions as we extend the datastore adapter set (no one size fits all).

Your suggested special field indicator makes sense to me.

**Comment by mingard** [comment]
Where translation is required, do we make sure a query to the collection mutates the output, reassigning the key that was inserted, or would an insert of `fooBar` return `foo-bar`?

**Comment by jimlambie** [comment]
@mingard seems like you're talking about property names?

**Comment by mingard** [comment]
Ah yes, I was. Misunderstood the issue!

**Comment by jimlambie** [comment]
https://github.com/dadi/api-couchdb/issues/4

**Comment by eduardoboucas** [comment]
> CouchDB does not allow field names with underscores at the beginning (e.g. _layout). We have a ticket open to prefix internal fields in 2.x, so the decision we make here will be passed into that ticket. Suggestion: select a different "special field" indicator, e.g. $layout.

I believe MongoDB doesn't allow field names starting with `$`. Could we stick with `_` and then leave it up to each adapter to translate accordingly? For example, CouchDB would decide that it would replace `_` with `$` when inserting a document and vice-versa when returning.

> CouchDB doesn't have a database > collection hierarchy as MongoDB does, so all collections will actually be created as databases. However CouchDB does not allow camelCased database names. For example, tokenStore would have to become token-store to work in CouchDB. Question: is this a problem, or could we simply have the CouchDB adapter translate between these under the hood? or do we define a convention for collection names that favours hyphenations over camelCase?

I'm also in favour of a internal translation approach, as it seems like the best way for us to prepare for any type of adapter that can come up in the future.

**Comment by nivlaps** [comment]
I think that the _adapter_ is the obvious place for this kind of translation; both really. It achieves the main goals perfectly:

**Comment by nivlaps** [comment]
I think that the adapter is the obvious place for this kind of translation; both really. It achieves the main goals perfectly:

**Comment by nivlaps** [comment]
I think that the adapter is the obvious place for this kind of translation; both really. It achieves the main goal perfectly; "allow a developer to switch data adapter and make zero changes to workspace files." Good call, Jim.

**Comment by jimlambie** [comment]
Thanks @josephdenne @mingard @eduardoboucas @nivlaps for the input! Someone just has to build these bits now...
