### ISSUE TITLE
Assets endpoint, configuration and reference

### ISSUE THREAD

**Issue by mingard** [dadi/api#222]
## Overview
Assets stored through API should be indexed and listed through a single endpoint.

- [Proposed changes](#proposed-changes)
- [Examples](#examples)
- [Query Examples](#query-examples)
- [Referencing](#asset-referencing)

### Proposed changes
- Add CDN block to API config (host, port, optional config endpoint path)
- CDN to have config endpoint, listing accepted image/asset types (https://github.com/dadi/cdn/issues/226)
- API to offer assets endpoint that accepts/rejects types based on CDN config, or local config types depending on existence of `cdn` param block

### Examples

basic asset block 
```json
{
  "assets": {
    "enabled": true
  }
}
```
using API mime 
```json
{
  "assets": {
    "enabled": true,
    "mimetypes": [
      { "image/jpeg": "public, max-age=86400" },
      { "text/css": "public, max-age=86400" },
      { "text/javascript": "public, max-age=86400" },
      { "application/javascript": "public, max-age=86400" }
    ]
  }
}
```

Using CDN config
```json
{
  "enabled": true,
  "cdn": {
    "host": "https://dadi-cdn.com",
    "port": 80,
    "path": "/config"
  }
}
```

#### All
```
http://dadi-api.com:80/assets
```

#### By type
```
http://dadi-api.com:80/assets?filter={"type": {"$in": ["jpeg", "mp4"]}}
```

### Asset Referencing
An additional field type of `asset` is required.

```json
"fields": {
  "image": {
    "type": "Asset",
    "label": "Image",
    "required": false
  }
}
```

We may want to allow validation specific to collections but should default to the API/CDN config `mimeTypes`.

```json
"fields": {
  "image": {
    "type": "Asset",
    "label": "Image",
    "required": false,
    "validation": {
      "mimetypes": [
        { "image/jpeg": "public, max-age=86400" }
      ]
    }
  }
}
```

**Comment by eduardoboucas** [comment]
Why does API need to have a CDN config block? Do I need to use CDN to have asset management in API?

**Comment by jimlambie** [comment]
I don't think this, or the referenced CDN issue, are required. I can't see what problem it solves.

1) we shouldn't need to link API or CDN
2) why does CDN have to report what mime types it accepts? It's sending assets, not accepting them
3) whether or not your document passes type validation is a project-specific implementation detail.

Top marks for the well-formatted issue, though 🌮

**Comment by mingard** [comment]
@eduardoboucas As stated in the description, it doesn't _need_ to have the CDN block, it's an optional way of syncing CDN mimeType configurations with an instance of API. 

@jimlambie 
1. Not a requirement, _optional_.
2. See 1.
3. What is this referring to?

Thanks!

**Comment by eduardoboucas** [comment]
I may be missing the point entirely, but all we're talking here is the ability for API to handle media upload and indexing of available assets, right?

If API would still use another location (say, Amazon S3) to physically place the files, all it would store would be a URL to this location. If this is the case, why does it need to even know that CDN exists? When you request assets, you get a list of URLs. If you want them to pass through CDN, you could add an afterGet hook that transforms the URLs before the response is sent out. 

As for mime types, I still don't get the requirement. You wouldn't load assets directly from API, so this should be handled by whoever hosts the files (or CDN, if it's being used)?

Again, apologies if I'm massively distorting the issue at hand.

**Comment by mingard** [comment]
Yes this is still very misunderstood.

- In publish we want to store assets in a collection
- we store filename, filepath, mimeType, width, height etc
- we will shortly start to use API to upload files
- we want API to not only store files, but index them
- we want the ability to specify accepted file types 
- we give the choice of accepting based on API config
- we also give the choice of accepting based on CDN config

It's really simple!

**Comment by jimlambie** [comment]
* `store files, and index them`: API writes to a media collection. That's indexed, no?
* `specify accepted file types`: can you do this in a hook?

I can't see the use case for checking CDN config to determine acceptability. Perhaps API's media block can be extended for this?

**Comment by mingard** [comment]
@jimlambie are you saying it already writes to a media collection? This is news to me. Does it store the required information (filename, path, width, height, mimeType and duration)?

It needs to store those and have restrictions on type. If we're going to the lengths of building media handling into API I don't think a hook is the answer. You could argue that media handling could've been an endpoint but the whole point here is that this becomes part of API core.

I'd like this to be able to handle restrictions on type. If we don't offer the option of syncing with CDN then fine, but it needs to come from somewhere so API config at the very least.

Can you put together documentation for retrieving media, and extend with the other required values. I need this for Publish.
