### ISSUE TITLE
Allow models to be a history collections

### ISSUE THREAD

**Issue by radswiat** [dadi/api#225]
### Expected behavior
let bookHistory = model('booksHistory');
bookHistory.find();
expect bookHistory to be defined

### Actual behavior
bookHistory is undefined
`Cannot read property 'find' of undefined`

### Package details
1.15.2
Windows

**Comment by jimlambie** [comment]
Hi @radswiat, thanks for the issue report.

History collections aren't actually designed to be queried directly. API can (currently) only load models that have collection schemas.

You could add a collection schema called booksHistory which might allow you to do this (i.e. a file in workspace/collections called `collection.booksHistory.json` which includes a similar set of fields to the original books collection)

Cheers!

**Comment by radswiat** [comment]
works as a charm! Thank you so much :)
Cheers!

**Comment by eduardoboucas** [comment]
Added in #527. Will go out in upcoming v5.0 of API. Docs will follow.

Thanks all!
