### ISSUE TITLE
Different results when using historyFilters with model

### ISSUE THREAD

**Issue by radswiat** [dadi/api#226]
### Expected behavior
  let draftRows = model.find( { status: 'draft' }, {
    compose: true,
    includeHistory: true,
    historyFilters: '{ "status": "staged" }'
  });

should return:
```
      "_id": "58b98bfbb0614bb42e293874",
      "documentId": "ObjectId(58b98bfab0614bb42e293860)",
      "categoryId": "ObjectId(a168865c-674d-48d8-9196-a14d41728a0c)",
      "status": "draft",
      ...
      "history": [
        {
          "_id": "58d100c2010183b49209fc26",
          "documentId": "ObjectId(58b98bfab0614bb42e293860)",
          ....
        }
}
```
### Actual behavior
```
      "_id": "58b98bfbb0614bb42e293874",
      "history": [
        {
          "_id": "58d100c2010183b49209fc26",
          "documentId": "ObjectId(58b98bfab0614bb42e293860)",
          ....
        }
}
```
Parent is missing data, it only have _id, when documentId, categoryId, status are gone.

All works fine when using url query:
`127.0.0.1:3001/1.0/presales/documentRows?filter={"status":"draft"}&includeHistory=true&historyFilters={"status":"staged"}`

### Package details
1.15.4
Windows

**Comment by jimlambie** [comment]
Hi @radswiat, yes, this is definitely a bug. I've started working on this one, hopefully will have a patch released soon. Thanks!
