### ISSUE TITLE
Add support for gzip

### ISSUE THREAD

**Issue by jimlambie** [dadi/api#241]
Gzipping data is an expensive process, the results of the gzip should be cached rather than caching the raw data and having to perform the gzip for every request.

API v1.15.x

**Comment by fra967** [comment]
Just to clarify, this ticket is about adding gzip support to API requests, and making sure that this happens before caching, right?

**Comment by jimlambie** [comment]
@fra967  @eduardoboucas  @abovedave  I'm not sure it _never existed_, as the DADI API provider in Web supports receiving compressed data from API. And at least one project I know of allows for content to be received compressed. So the question is... was it removed?
