### ISSUE TITLE
Query &fields= doesn't work with &filter=

### ISSUE THREAD

**Issue by radswiat** [dadi/api#252]
### Expected behavior

Below query should return filtered data with only _id and data field.
```
127.0.0.1:3001/1.0/presales/documentRows?filter=[{"$match":{"documentId":"1","status":"staged"}}]&fields={"data":true}
```

### Actual behavior
fields parameter is ignored, and whole filtered data is returned ( filter works, fields don't ).
Whole query works when separated into 2 calls
- `&fields={"data":true}` works just fine without filter=

### Package details
Mac,
"@dadi/api": "1.16.3",
and
"@dadi/api": "1.15.5"

**Comment by jimlambie** [comment]
Hi @radswiat  - could you try using `{ "field": 1 }` rather than `true`? 

For example:

```
127.0.0.1:3001/1.0/presales/documentRows?filter=[{"$match":{"documentId":"1","status":"staged"}}]&fields={"data":1}
```

Should return only the fields `_id` and `data`

**Comment by jimlambie** [comment]
Ah! It's an aggregation query. My mistake! We'll need to add a $project stage to your query:

e.g. `{ $project : { _id: 0, title : 1 , author : 1 } }`

```
127.0.0.1:3001/1.0/presales/documentRows?filter=[{"$match":{"documentId":"1","status":"staged"}},{ $project:{ _id: 0, data:1 }}]
```

**Comment by radswiat** [comment]
Hey, great !
I'll wait for the feature then :)
Cheers!

**Comment by jimlambie** [comment]
Oh, you don't need to wait! It _should_ work like that already ^

```
http://127.0.0.1:3001/1.0/presales/documentRows?filter=[{"$match":{"documentId":"1","status":"staged"}},{ $project:{ _id: 0, data:1 }}]
```

**Comment by jimlambie** [comment]
@radswiat you can join our Slack channel if you'd like, you'll be able to get faster help :)

Sign up at http://dadi-chat.herokuapp.com/

**Comment by jimlambie** [comment]
Closing as the question was answered.
