### ISSUE TITLE
hook generation endpoint

### ISSUE THREAD

**Issue by mingard** [dadi/api#254]
Hooks currently can't be listed, created or updated through an endpoint.

Request to introduce this feature In an identical method to the current _custom endpoint_ RESTful endpoint as per discussion on Slack with @eduardoboucas

**Comment by jimlambie** [comment]
Do you mean adding `/api/hook/hookName/config` as we have for collections and endpoints?

**Comment by mingard** [comment]
@jimlambie @eduardoboucas informs me that part of this ticket exists and he is taking care of the rest.

**Comment by eduardoboucas** [comment]
@jimlambie That's correct. I believe that endpoint supports only `GET` at the moment, so I can add `POST` and `PUT` if you're cool with that.

**Comment by jimlambie** [comment]
Closed via https://github.com/dadi/api/commit/450540d973dd12ed49e55a8e3a225df466cc0ca0
