### ISSUE TITLE
Automated release benchmarking

### ISSUE THREAD

**Issue by mingard** [dadi/api#255]
For current and historic versions of API it would be useful to generate useful headline benchmarking statistics, including:
- Performance against previous versions
- Various tests
 - Concurrent requests
 - Resource usage
 - read/writes per second
- multiple performance snapshots on each supported Node/Mongo versions

**Comment by jimlambie** [comment]
@mingard can you provide any more information? Do you have any favourite tools that provide this information?

**Comment by mingard** [comment]
@jimlambie not at present. I'll be researching this soon

**Comment by eduardoboucas** [comment]
Moved to our internal product-wide backlog.

**Comment by jimlambie** [comment]
https://trello.com/c/uMo8ZHG9/17-application-benchmarking
