### ISSUE TITLE
Sibling and sub Reference fields combined fail to resolve

### ISSUE THREAD

**Issue by mingard** [dadi/api#262]
In the following example, the `region` field in `houses` never resolves.
Overview of Reference hierarchy
- houses
  - country
  - region

- region
  - country

- country *NONE*

*Note*: If you remove the `country` reference from the `region` collection, houses resolve properly, _or_ if you set `settings.compose` to `false in the `regions` collection.

### Houses
```json
{
  "fields": {
    "country": {
      "type": "Reference",
      "label": "Country",
      "settings": {
        "collection": "countries"
      }
    },
    "region": {
      "type": "Reference",
      "label": "Region",
      "settings": {
        "collection": "regions"
      }
    }
}
```
### Regions
```json
{
  "fields": {
    "name": {
      "type": "String",
      "label": "Name"
    },
    "country": {
      "type": "Reference",
      "label": "Country",
      "settings": {
        "collection": "countries"
      }
    }
}
```
###Country
```json
{
  "fields": {
    "name": {
      "type": "String",
      "label": "Name"
    }
}
```

**Comment by jimlambie** [comment]
@mingard I'm going to assume you're on 1.16.3. Would you be able to update to 1.16.4 and see if this version resolves your issue?

**Comment by jimlambie** [comment]
Closed via https://github.com/dadi/api/commit/450540d973dd12ed49e55a8e3a225df466cc0ca0
