### ISSUE TITLE
Add `updatedDocs` to delete hook events

### ISSUE THREAD

**Issue by mingard** [dadi/api#263]
When deleting a document, the only parameter that is required is the `_id`, however the `beforeDelete` and `afterDelete` hooks may need access to document data. 

In a similar method to the `updatedDocs` array used in `beforeUpdate`, append the data argument with the full deleted document.

Thoughts @eduardoboucas?

**Comment by eduardoboucas** [comment]
Totally possible. It would involve running an extra query to extract the documents first, but that's what we're doing on the update method anyway.

**Comment by mingard** [comment]
@eduardoboucas great, thank you. If that's okay then, this would be very useful!

**Comment by eduardoboucas** [comment]
To confirm, `beforeDelete` and `afterDelete` would both receive the same data, which would be the result of a find operation with the query specified. Right?

**Comment by mingard** [comment]
That's exactly it

**Comment by jimlambie** [comment]
@mingard adding this to a property called `deletedDocs` .... is that ok for you?

**Comment by mingard** [comment]
@jimlambie ideal, thanks!
