### ISSUE TITLE
Hooks to receive error block

### ISSUE THREAD

**Issue by mingard** [dadi/api#273]
Under some conditions, a hook may need to be able to block further hooks and the rest of the request by accessing the error parameter. 

For example, where a field needs to be unique, which currently sits outside of the field validation controller, the hook would need to append the error block with something similar to the core validation or required field error message.

This would also allow us to return suggestions or other appropriate information in the payload.

```json
{
  "errors": [
    {
      "field" : "Title",
      "message": "Title must be unique.",
      "suggestion": "Foo 2"
    }
  ]
}
```

This relates to concept in https://github.com/dadi/api/issues/272

**Comment by jimlambie** [comment]
The support for custom hook errors introduced in API 2.2.0 covers the use case suggested here. Closing.
