### ISSUE TITLE
Add logging level to config

### ISSUE THREAD

**Issue by jimlambie** [dadi/api#28]
Currently the logging level cannot be controlled, resulting in all log statements being sent to the log file. 

Modify as per Web, which has the following config option:

```
logging: {
    level: {
      doc: "Sets the logging level.",
      format: ['debug','info','warn','error','trace'],
      default: 'info'
    }
}
```

**Comment by fra967** [comment]
I have been testing this latest patch and i don't see any difference in the log output when setting level "debug" vs. "error"; in both cases, all queries are both output to the log and to the console (while I would expect "error" level to suppress query information)

**Comment by fra967** [comment]
Still seeing debug messages (level 30) in production logs when log level set to error (50)
