### ISSUE TITLE
Add prestart script

### ISSUE THREAD

**Issue by mingard** [dadi/api#281]
### Expected behavior

Running before start, the prestart script will
- Check for config
- Check for required directories
- Create missing directories
- Create missing config

**Comment by jimlambie** [comment]
Already creates required directories at startup

**Comment by jimlambie** [comment]
We have a post install script which copies a sample config. See if you can use that for the startup check

**Comment by mingard** [comment]
@jimlambie I get this error on startup. I don't think the script to create directories is working.
```
Error: ENOENT: no such file or directory, scandir '/usr/dadi-api/workspace/collections'
```

**Comment by jimlambie** [comment]
@mingard https://github.com/dadi/api/issues/201 ... will do now

**Comment by eduardoboucas** [comment]
Main install point is now CLI, which covers all of this. API should also be checking most of the above and will throw an error when something is missing. We might need to tidy up some of the error messages, but let's capture that on a separate ticket if we find the need for it.
