### ISSUE TITLE
Improve hooks error reporting

### ISSUE THREAD

**Issue by fra967** [dadi/api#289]
Currently (API 1.16.6 and API 2.0 rc1) when a hook fails the error message is logged, for example

`Hook Error',\n    details: 'The hook \\'xxxx\\' failed: \\'TypeError: Cannot read property \\'toString\\' of undefined\\''`

However no additional information is available in order to troubleshoot the error, not even a line number of where the error has been raised

The only option is to add a manual console.log to trap the whole error in
https://github.com/dadi/api/blob/master/dadi/lib/model/hook.js#L38

Please add the first line of the error details (which should include the offending file and line number) in the error message

**Comment by jimlambie** [comment]
@eduardoboucas 
 https://github.com/dadi/api/commit/d103f626cdd6b27b7407b8fd8421021ff038092e and API v2.0.0 introduces the addition of the first line of the stack trace. Closing this issue, we can raise a new one when it comes time to include greater detail in the API errors across the board.

**Comment by fra967** [comment]
is it just me or this has been removed in api 2.1.2?

**Comment by eduardoboucas** [comment]
@fra967 Not intentionally. We did add the ability for hooks to throw custom errors, which I suspect might be causing the issue you're seeing.

Could you share the output of the error you're seeing?

**Comment by fra967** [comment]
Sample response (API 2.1.2)
```
{
    "success": false,
    "errors": [
        {
            "code": "API-0002",
            "title": "Hook Error",
            "details": "The hook 'slugify' failed: 'undefined'",
            "docLink": "http://docs.dadi.tech/errors/api/API-0002"
        }
    ]
}
```

**Comment by eduardoboucas** [comment]
Do you have any information you can share about the nature of the error being thrown? I wasn't able to replicate this behaviour.

I added a simple runtime error to a hook (calling a function that doesn't exist), and I get this:

```
{
    "success": false,
    "errors": [
        {
            "code": "API-0002",
            "title": "Hook Error",
            "details": "The hook 'slugify' failed: 'functionThatDoesNotExist is not defined\n    at Hook.module.exports (/Users/eduardoboucas/Sites/publish-api/workspace/hooks/slugify.js:20:3)'",
            "docLink": "http://docs.dadi.tech/errors/api/API-0002"
        }
    ]
}
```

**Comment by jimlambie** [comment]
Closed by https://github.com/dadi/api/commit/a5cb25338ac3868e709849c5a2223368b09294b2
