### ISSUE TITLE
Add internal fields in model

### ISSUE THREAD

**Issue by jimlambie** [dadi/api#300]
Internal fields such as `createdAt` are added to the incoming data in the controller, so if an insert is performed using the model instance, no internal fields are added.

Suggest we add these in the model, not in the controller.

/cc @eduardoboucas  thoughts?

**Comment by eduardoboucas** [comment]
Absolutely. Perhaps this is something we can tackle along with #141 on the next major release?

**Comment by fra967** [comment]
why don't we use just one field (whose name is configurable) and then all internal fields are elements of that single field?
alternatively, please make the prefix configurable
