### ISSUE TITLE
DELETE response by default

### ISSUE THREAD

**Issue by mingard** [dadi/api#314]
Open for discussion:

### Current behaviour
I believe there is a flag to enable a return body (I don't know what it is, or if it's documented).

### Proposed behaviour
I would like to make a response for a DELETE call default, giving some stats on the number of documents deleted and the number remaining.

**Comment by jimlambie** [comment]
@mingard the config option is `"feedback": true`.

* when `false` it returns HTTP 204 No Content
* when `true` it does return the number of documents deleted

**Comment by mingard** [comment]
@jimlambie I was actually hoping that we could change the default behaviour to `true` inline with other method requests. Also for it to return full meta including total documents (obviously pagination figures aren't relevant here).

Thoughts?

**Comment by eduardoboucas** [comment]
Looks good to me! Adds more info and avoids breaking changes. :tada:

**Comment by mingard** [comment]
Would changing the default, where no `feedback` param is set to `true` be considered a breaking change? 

I'd still rather a returned body was the default, not just a `204 No Content` header.

**Comment by eduardoboucas** [comment]
> Would changing the default (where no feedback param is set, default to true) be considered a breaking change?

It would, since we'd have to change the response code from `204` to `200`.

**Comment by mingard** [comment]
Gotcha. Would still prefer a meta response body by default.

**Comment by mingard** [comment]
What is the justification for feedback-by-default for `GET`, `PUT`, `POST` but not `DELETE`?

I've just been testing and it appears that a failed delete (invalid query) returns the same response header. To differentiate between an accepted and unaccepted filter, it would also be useful to return either 
- 202 (Accepted) 
- 200 (Accepted with response)
- 204 (No Content) when feedback is false and accepted
- 406 (Not Accepted) when feedback is false and query is not accepted

**Comment by jimlambie** [comment]
Sending a `204` as the response for a `DELETE` is (or was) considered enough feedback. `GET` obviously needs to return a response body, and `PUT` & `POST` are either updating or inserting data so have something to report on. A `DELETE` removes data, and therefore there is nothing left to say other than "done".

**Comment by jimlambie** [comment]
We send a `400` if the query is malformed

**Comment by mingard** [comment]
> therefore there is nothing left to say other than "done".

Feedback as to what has been done is just as useful for a `DELETE` as a `PUT`, therefore should be default. If there is no extra step to know how many documents have been updated, why should there be an extra step to know how many documents have been deleted?

**Comment by jimlambie** [comment]
Ok, I get where you're coming from. Unfortunately, this won't be included in the next release (Version 3.0) as a default - until it is you'll have to run with `"feedback": true`.

**Comment by mingard** [comment]
Okay, it's not urgent so let's leave this open until then.

**Comment by jimlambie** [comment]
I'm actually modifying this.

The response (with feedback: true) will return a totalCount property that is equal to the number of documents remaining in the collection.

```
{
  status: 'success',
  message: 'Documents deleted successfully',
  deleted: 1, // documents deleted
  totalCount: 100 // remaining documents in the collection
}
```
