### ISSUE TITLE
API does not recover from a temporary database connection interruption

### ISSUE THREAD

**Issue by fra967** [dadi/api#327]
If the database (MongoDB) goes temporarily down API does not resume the connection but requires to be restarted

### Steps to reproduce the problem
- start API
- send a request - works as expected
- stop database
- send a request - 500 error is returned after 30 seconds
```
MongoError: failed to reconnect after 30 attempts with interval 1000 ms
        at Connection.<anonymous> (/var/www/bauer-radio-api/api/node_modules/mongodb-core/lib/connection/pool.js:318:15)
```
- restart database
- send a request - 500 error is returned 
```
MongoError: Topology was destroyed
        at nextFunction (/var/www/bauer-radio-api/api/node_modules/mongodb-core/lib/cursor.js:540:25)
```
- API can resume only if manually restarted

### Expected behaviour

API to resume functionality when the database connection is back.
It would also be useful to have control on the database connection attempts (30 every 1000 ms may be questionable in HA environments)

### Actual behaviour

API returns 500 

### Package details

API 2.2.4 
Node 6.11.2

**Comment by jimlambie** [comment]
This might be a useful solution to investigate https://www.npmjs.com/package/recovery

**Comment by fra967** [comment]
This is also applicable to Web when it uses MongoDB for sessions data
