### ISSUE TITLE
Allow createFromComposed when updating Reference fields

### ISSUE THREAD

**Issue by jimlambie** [dadi/api#333]
When creating new documents it is possible to fill a Reference fields with new, non-existing subdocuments. API creates a new document in the referenced collection and replaces the subdocument with the new identifier.

```
{
  "makes": [
    { "name": "Ford" }
  ]
}
```

becomes

```
// referenced collection
{
  "_id": ""1234567890",
  "name": "Ford"
}

// referencing collection 
{
  "makes": [
    "1234567890"
  ]
}
```

The same process does not happen on PUT requests. In this case whatever is passed in the update request body is used as the new value for the field.

```
{
  "makes": [
    { "name": "Ford" }
  ]
}
```

becomes

```
// referenced collection
[]

// referencing collection 
{
  "makes": [
    { "name": "Ford" }
  ]
}
```

The suggestion is that when passing an update request body such as the below will create documents that have no identifier:

```
{
  "makes": [
    { "_id": "1234567890" }
    { "name": "Mazda" }
  ]
}
```

**Comment by mingard** [comment]
@jimlambie looks good to me! Thank you.
