### ISSUE TITLE
publicUrl output required

### ISSUE THREAD

**Issue by mingard** [dadi/api#335]
To reduce cross-internet traffic when running Publish on the same instance as API, the hostname for the API should be set to a local address or hostname e.g. 127.0.0.1.

Publish pushes media via ajax, which means it needs an exposed public hostname. As this is a property that can be set in API config under `publicUrl.hostname` it would be beneficial to add this to the collection endpoint at `/api/collections` (or somewhere else - I'm open to suggestions).

**Comment by eduardoboucas** [comment]
This information is available on the `/api/config` endpoint.

**Comment by jimlambie** [comment]
@mingard sounds like this is already possible with existing calls, ok to close the issue?

**Comment by mingard** [comment]
@eduardoboucas Is it? I couldn't see this anywhere.

**Comment by mingard** [comment]
Update: I can see it on some APIs I'm testing with, but others don't appear to have it. Is this a configuration option?

**Comment by jimlambie** [comment]
@mingard  https://github.com/dadi/api/blob/develop/config.js#L13-L19

**Comment by mingard** [comment]
@jimlambie Okay. The two choices I can see that would guarantee that Publish can see these parameters are:
1. Revise this ticket to add the publicUrl parameters to the collection config endpoints.
2. Have Publish throw a warning when the api config endpoint is disabled.

**Comment by jimlambie** [comment]
Can the API config endpoint be disabled? I don't think it can. You need a certain version of API though, which is true for Publish in general as far as I can tell. Suggest 2.2.5 is the minimum version required.

I don't think we'll add the publicUrl to the collection endpoint config.

**Comment by mingard** [comment]
@jimlambie if you're certain it can't be disabled then that's fine. Your minimum version recommendation is the best solution, and no need to add the publicUrl to any other endpoint.
