### ISSUE TITLE
Search acceptance tests

### ISSUE THREAD

**Issue by mingard** [dadi/api#337]
Search needs acceptance tests for:
- Create article indexes on POST
- Updating article indexes on PUT
- Removing article indexes on DELETE
- Storing only unique words in search word collection
- Retrieving articles based on search query param

**Comment by mingard** [comment]
@jimlambie Assigned to you as discussed. These should be enough for now 😸. Thank you.

**Comment by eduardoboucas** [comment]
Let's move this to #352. Closing!
