### ISSUE TITLE
Authentication is bypassed in endpoints

### ISSUE THREAD

**Issue by fra967** [dadi/api#37]
### Expected behavior
All endpoints to return 401 if no authentication bearer is passed in the HTTP headers

### Actual behavior
Endpoints are returning data with a simple GET request

### Steps to reproduce the problem
Just browse to these endpoints (GET, without authentication headers)

http://api.test.lifestyle.one/1.0/hubArticles?count=2&page=1
http://api.whatcar.tech/1.0/car-rivals

### Package details
dadi/api 1.3.0

**Comment by dark12222000** [comment]
This is configurable by a setting. Some endpoints need to be public but most locked down.

**Comment by fra967** [comment]
Only this endpoint seems to enforce authentication
https://github.com/dadiplus/bauer-lifestyle-serama/blob/dev/workspace/endpoints/1.0/endpoint.article.js
but I could not find anything in the code that is particularly different from the other open endpoints.
Any idea if this is configurable and where?
And shouldn't by default be locked down?
From this open endpoint
https://github.com/dadiplus/bauer-lifestyle-serama/blob/dev/workspace/endpoints/1.0/endpoint.docs.js
it seems that a specific setting needs to be applied to bypass authentication
```
// ensure requests bypass authentication
module.exports.model = {};
module.exports.model.settings = { "authenticate" : false };
```

**Comment by jimlambie** [comment]
Correct, it is configurable in the same way that caching is:

```
module.exports.model = {
  settings: {
    authenticate : true,
    cache : true
  }
}
```

The linked car-rivals endpoint is configured to cache only:
https://github.com/dadiplus/whatcar-com/blob/master/api/workspace/endpoints/1.0/endpoint.car-rivals.js#L8-L12

Perhaps it should be set by default, yes. I'll add it in the next release.
