### ISSUE TITLE
Field matchType error

### ISSUE THREAD

**Issue by mingard** [dadi/api#382]
When inserting email data into a field with this schema:

```json
   "email": {
      "type": "String",
      "label": "Email",
      "comments": "Email address",
      "example": "jdoe@dadi.tech",
      "validation": {
        "regex": {
          "pattern": "^[a-z0-9._%+-]+@[a-z0-9.-]+\\.[a-z]{2,4}$"
        }
      },
      "required": true,
      "message": "must be a valid email address"
    }
```

I get the error 
```
Cannot read property \\'matchType\\' of undefined\\n    at /project/path/node_modules/@dadi/api/dadi/lib/model/utils.js:89:26'
```

## Further diagnosis

In my current env I have a collection called `collection.users.json` which exists in database `my-api`. 

There is also a collection in `vtests` called `collection.users.json`.

`getSchemaOrParent` seems to be retrieving the wrong collection schema, and therefore is not finding a field `email` in the schema.

For reference, I'm using the schema defined in the `api-install` script of publish, found here: https://github.com/dadi/publish/blob/master/scripts/api-install/collections/collection.users.js

**Comment by jimlambie** [comment]
@mingard what does the "paths" property look like in your config ?

**Comment by mingard** [comment]
@jimlambie I don't know which project I was testing this with. Are you wondering if I'd supplied the `paths.collections` parameter, and whether a lack of this could be the cause of API defaulting to the collection in the node_module workspace?

**Comment by jimlambie** [comment]
@mingard yep, that's what I was thinking. Which makes it more relevant to one of the open issues for getting the config rightg

**Comment by mingard** [comment]
@jimlambie That's probably what happened. I recently had the same issue with hooks, where a project collection was looking for a hook in the node_modules hook directory because I hadn't defined it. A bit painful to diagnose actually. I wonder if there's anything we can do there. Regarding this ticket, I'll close.

**Comment by eduardoboucas** [comment]
> I wonder if there's anything we can do there

100%! https://github.com/dadi/api/issues/371
