### ISSUE TITLE
After cloning API repository cannot start server due to missing @dadi/api-mongodb datastore

### ISSUE THREAD

**Issue by davidmacp** [dadi/api#387]
### Expected behavior
Following the current README.MD expected a clean install and start.

After cloning API Product and running `npm install` followed by `npm start`, the API should start as expected without any error.

### Actual behavior
Running `npm install` is successful
Running `npm start` gets the following error:
`Error: API configured to use a datastore that has not been installed: "@dadi/api-mongodb"`

### Steps to reproduce the problem
1. `git clone https://github.com/dadi/api.git`
2. `npm install`
3. `npm start`
4.  Error received - `Error: API configured to use a datastore that has not been installed: "@dadi/api-mongodb"`

[npm-debug.log](https://github.com/dadi/api/files/1742728/npm-debug.log)

### Package details
node v6.11.2
npm  v3.10.10
@dadi/api@3.0.0

### Subsequent Notes
Running `npm install @dadi/api-mongodb` fixes the initial error.
Can/should this step be added to the README.MD?

**Comment by jimlambie** [comment]
@eduardoboucas what do you think about this? we use the in-memory connector for tests, and if using CLI we get api-mongodb anyway (I think?). Straight out of the repo, what should we do?

**Comment by eduardoboucas** [comment]
We do get `@dadi/api-mongodb` when installing via CLI. I'd say that running API straight out of the repo will be used for development purposes only, so a note in the README saying that a data connector package must be installed would be the best course of action.

**Comment by eduardoboucas** [comment]
The README now specifies that a data connector module is a requirement to use API. Can this be closed?
