### ISSUE TITLE
Make the apiVersion filter configurable

### ISSUE THREAD

**Issue by fra967** [dadi/api#39]
Every API query passes an
`"apiVersion" : "1.0"`
down to Mongo

This adds unnecessary load (most applications in production to not distinguish by apiVersion).

Although it is important to store this value in each document, its filtering should be made configurable.

Temporary workaround is to add an index to the apiVersion field.

### Package details
1.3.0

**Comment by jimlambie** [comment]
Hi @fra967 ,

Any chance you could give me some Mongo benchmarks for performance with and without this added query? I'd like to understand what sort of load we're looking at for each added filter query.

Cheers!

**Comment by fra967** [comment]
@jimlambie this is from Empire test MongoDB
```> db.system.profile.find({ns:"api_empire_com.articles"},{query:1,millis:1}).sort({ts:-1}).limit(2)
{
        "query" : {
                "url" : "/people/tim-roth/tim-roth-finds-mr-right/"
        },
        "millis" : 60
}
{
        "query" : {
                "url" : "/people/tim-roth/tim-roth-finds-mr-right/",
                "apiVersion" : "v1"
        },
        "millis" : 152
}
```

**Comment by jimlambie** [comment]
@fra967 have added to config:

(default is false)

```
query: {
    useVersionFilter: false
}
```
