### ISSUE TITLE
Unable to filter by schema default ISO dates

### ISSUE THREAD

**Issue by abovedave** [dadi/api#394]
### Expected behavior

Return an appropriate subset of results, when I pass a filter with the date format matching the schema default.

### Actual behavior

No results returned.

### Steps to reproduce the problem

Example field schema:

Set a date field in the schema:

```json
"date": {
  "type": "DateTime",
  "required": true,
  "label": "Date & Time"
}
```

Create some test content with varying dates, then attempt to pass a filter e.g.,

```
{"date":{"$gt":"2016-01-01T00:00:00.000Z"}}
```

or a range

```
{"date":{"$gte":"2018-02-04T08:57:23.191Z","$lte":"2018-04-05T07:57:23.193Z"}}
```

**In addition it might be worth setting the default date format in the schema to be `"format": "unix"` to match the auto-generated fields such a `_createdAt`** 

### Package details

DADI API 3.x

**Comment by abovedave** [comment]
[articles.txt](https://github.com/dadi/api/files/1784356/articles.txt)

**Comment by abovedave** [comment]
The work around is to set all dates as unix milliseconds, and pass the filter as unix too

```json
date": {
  "type": "DateTime",
  "format": "unix",
  "required": true,
  "label": "Date & Time"
}

**Comment by eduardoboucas** [comment]
This has been covered by acceptance tests in https://github.com/dadi/api/pull/399/commits/651f9fed1d8969b5098818e98061c0bea33b3d48#diff-950b9a454b1a9169a2c95dcba4747789R399 and will go out with API 3.1.
