### ISSUE TITLE
Ability to sort by nested keys

### ISSUE THREAD

**Issue by abovedave** [dadi/api#398]
Similar to #397, but sorting by nested keys e.g., 

```json
"sort": {
   "category.updatedAt": 1
}
```

**Comment by eduardoboucas** [comment]
I don't think this will be possible. For the parent collection, `category` is just a string (or array of strings), and it won't know anything about the content or structure of any referenced documents, so we can't have that as a sorting factor at the database engine level.

Do you concur, @jimlambie?

**Comment by jimlambie** [comment]
@eduardoboucas @abovedave I concur, yes. This seems like something where you could consume the data first and then sort using your own method once the data is in the client application.

**Comment by eduardoboucas** [comment]
Sorry, DL. 🔪💀
