### ISSUE TITLE
before & after id pagination

### ISSUE THREAD

**Issue by abovedave** [dadi/api#412]
Was pondering this idea from reading [this article on twitter pagination](https://developer.twitter.com/en/docs/tweets/timelines/guides/working-with-timelines).

I think it would be useful to offer additional pagination offsets for returning results. In addition to the timeline-style pagination above (they use `max_id` and `since_id`) it would be also useful in constructing datasources for 'next' and previous style navigation techniques.

E.g., passing an article id as `before` or `after` along with a `count` to get the next document described by the sorting technique. Alternatively we could do something like pass an `id` and an `offset` (-1, 1 etc)

**Comment by jimlambie** [comment]
I was thinking about something similar a while ago. Not the offset part - but agree this could well be an issue if you have new data continually arriving. In that specific case, specifying an id as a starting point makes sense.

What might be a useful addition is adding the pagination links into the metadata directly. This has the benefit of not requiring the web developer at the other end to do any pagination maths; they'd simply render out the links we provide.

GitHub send pagination links in the response header (see below), but I'm not sure about this. It's metadata and we _have_ a metadata block so why not use that?

```
"headers": {
  "Link": <https://api.github.com/user/repos?page=3&per_page=100>; rel="next", 
  <https://api.github.com/user/repos?page=50&per_page=100>; rel="last"
}
```
An approach like this for API might look like:

```
{
  "results": [
    {
       "title": "Big"
    }
  ],
  "metadata": {
    "limit": 100,
    "totalCount": 3000,
    "totalPages": 30,
    "links": {
      "next": "http://your-api.com/1.0/movies/eighties-classics?page=3&count=100>",
      "last": "http://your-api.com/1.0/movies/eighties-classics?page=30&count=100>"
     }
  }
}
```

**Comment by abovedave** [comment]
The headers thing is interesting, I think the stems from the SEO world. Is there a scenario where it would be useful to `HEAD` request without needing the results? Perhaps that is a separate bit of work.
