### ISSUE TITLE
Multi-lang support

### ISSUE THREAD

**Issue by jimlambie** [dadi/api#433]
### Suggested approaches 

There are a couple of options in the mix for specifying languages in API:

1) define the languages and the fields in the collection schema

For example, the following creates 2 translations for the `body` field, one in Portuguese, the other in French:

```json
{
  "fields": {
    "body": {
      "type": "String"
    },
    "body:pt": {
      "type": "String",
      "settings": {
        "translation": {
          "field": "body",
          "language": "Portuguese"
        }
      }
    },
    "body:fr": {
      "type": "String",
      "settings": {
        "translation": {
          "field": "body",
          "language": "French"
        }
      }
    }
  }
}
```

A request to API for the Portuguese version might look like `/1.0/db/collection?fields={"body":1}&lang=pt`, where API would ask the database for `body:pt` and `body` (the latter being the fallback).

Send `lang=all` in the query would get all the languages (in case you want to edit them all at once in Publish, for example). The advantage of this is that API would know what languages there are for each field before making a query. In the example above, if you send `lang=pt`, API would know that `body:fr` would never be required and could explicitly tell the data connector to exclude it. The above could also be like this, which is shorter:

```
{
  "fields": {
    "body": {
      "type": "String",
      "settings": {
        "i18n": {
          "body:fr": "French",
          "body:pt": "Portuguese"
        }
      }
    }
}
```
...less clear that those will be new fields, but more concise

2) A solution that might avoid the requirement to specify each language in the collection schema is to define the supported languages globally. Somewhere we configure that this API supports `["fr", "pt"]`, with the ability to set a default (such as `en`), and then adopt the convention that `fieldOne` contains the default language, `fieldOne:fr` contains the `fr` translation, etc.

### Configuring API language support

The API configuration could be extended to provide settings for the supported languages, and to indicate which is considered the fallback:

```
"languages": [
  {
    "code": "en",
    "name": "English",
    "locale": "en_GB",
    "default": true
  },
  {
    "code": "de",
    "name": "German",
    "locale": "de_DE"
  },
  {
    "code": "ar",
    "name": "Arabic",
    "locale": "ar_EG",
    "direction": "rtl"
  }
]
```

A new endpoint `/api/languages` could be added to assist consumer applications in determining the languages that are available.

### Response delivered to a consuming application

*If* you specify a `lang` parameter, it each translated field would be returned using the original field name (such as `fieldOne`) and meta field (`"_i18n": {}`) within the document would indicate whether that is the language you requested or the fallback:

Example request:

**/1.0/news/articles?lang=fr**

```
{
  "results": [
    {
      "_id": "doc-without-fr-translation",
      "_i18n": {
        "body": "en"
      }
      "body": "Thank you very much!"
    },
    {
      "_id": "doc-with-fr-translation",
      "_i18n": {
        "body": "fr"
      }
      "body": "Merci beaucoup!"
    }
  ]
}
```

An alternative to specifying the language parameter in the querystring is to utilise the `Accept-Language` and `Content-Language` HTTP headers.

### Things to consider
* validation rules for a translated field - if there's a min/max length requirement, this could well be different for different languages

**Comment by jimlambie** [comment]
@eduardoboucas @abovedave please add your thoughts to this ticket, or give it a 👍

**Comment by abovedave** [comment]
I can see a combo of 1) and 2) being useful.

Similar to the way in Web & API we can specify to return specific fields only `title: 1` or exclude specific fields `title: 0`. Being able to globally allow translations for all fields, but then exclude specific ones e.g., url slug text, date field, image file field which would be the same across all languages.

**Comment by jimlambie** [comment]
So you're suggesting that we don't need to add new fields to the schema for each language, but fields should be able to indicate if they're translatable or not

**Comment by abovedave** [comment]
yeah perhaps have a collection wide `setting` too

**Comment by eduardoboucas** [comment]
I think the logic I used for suggesting the first approach was flawed. It's perfectly feasible to declare the languages globally (e.g. in the main config) and still ensure you don't ask for unnecessary fields from API. Imagine the following document:

```json
{
  "_id": "123456",
  "slug": "some-article",
  "title": "This is a title",
  "title:pt": "Isto é um título",
  "body": "This is the article body",
  "body:pt": "Isto é o corpo do artigo"
}
```

There are fields you want to translate, like `body` and `title`, and others you don't, like `_id` or `slug`. 

## Request 1

When you make a request *without* a `lang` parameter, you get all the fields back:

**GET /1.0/db/collection**

```json
{
  "results": [
    {
      "_id": "123456",
      "slug": "some-article",
      "title": "This is a title",
      "title:pt": "Isto é um título",
      "body": "This is the article body",
      "body:pt": "Isto é o corpo do artigo"
    }
  ]
}
```

## Request 2

If you ask for a specific language, you'll get a `_i18n` meta field indicating which fields have been translated.

**GET /1.0/db/collection?lang=pt**

```json
{
  "results": [
    {
      "_id": "123456",
      "_i18n": {
        "title": "pt",
        "body": "pt"
      },
      "slug": "some-article",
      "title": "Isto é um título",
      "body": "Isto é o corpo do artigo"
    }
  ]
}
```

## Request 3

You can ask for a specific language *and* limit the fields you're getting back.

**GET /1.0/db/collection?lang=pt&fields={"slug":1,"title":1}**

```json
{
  "results": [
    {
      "_id": "123456",
      "_i18n": {
        "title": "pt"
      },
      "slug": "some-article",
      "title": "Isto é um título"
    }
  ]
}
```

When we detect the `fields` parameter, we need to go through each included field and add all possible lang variations. So when API sees `fields={"slug":1,"title":1}` and `lang=pt`, it needs to internally transform the fields query to `fields={"slug":1,"slug:pt":1,"title":1,"title:pt":1}`. It doesn't matter that `slug` is translated, API just won't get a translated field back.

Even in the case of *Request 2*, where no `fields` parameter is supplied, we can still optimise the API query. If we get `lang=pt`, we can change `fields` to explicitly include every single field in the collection schema and their `pt` variations. This will automatically exclude any languages we're not interested in and return the `pt` version of any fields that have that translation.

---

Does this make sense? 😇

**Comment by eduardoboucas** [comment]
Done in 4.1.0.
