### ISSUE TITLE
Filtering by a property value of a composed object returns error

### ISSUE THREAD

**Issue by fra967** [dadi/api#435]
### Expected behavior
Consider a collection book with a field named `Status`, whose value can be "published" or "draft", and reference this collection from `event`.

Filtering all events for books whose status is published should return the relevant books
`/v1/library/event?filter={"book.publishStatus.status":"published"}`

### Actual behavior
Error 400 Bad Request

### Steps to reproduce the problem
https://github.com/dadi/api/commit/bae0ddd007c0ca17d8a11ce8b2f168228768cbd8

### Package details
API 3.1.2 (also applicable API 2.x)
node 6.14.2

**Comment by eduardoboucas** [comment]
I'll investigate.

**Comment by eduardoboucas** [comment]
Sorry @fra967, I don't know why this test was removed as part of the Reference field refactoring done in 3.1.0.

The issue has been fixed, the test has been added back and it was released as [API 3.2.1](https://www.npmjs.com/package/@dadi/api).
