### ISSUE TITLE
Enable CORS by default

### ISSUE THREAD

**Issue by eduardoboucas** [dadi/api#438]
I think we should make the `cors` config property enabled by default. It's expected that using API from a client-side application will be a very common use case, which requires developers to explicitly enable CORS in their API configs. I don't see any harm in making that enabled by default.

https://github.com/dadi/api/blob/develop/config.js#L360

What do you think @jimlambie?

**Comment by danwdart** [comment]
Should this now be closed?

**Comment by eduardoboucas** [comment]
Indeed! Thanks @danwdart.
