### ISSUE TITLE
[2.3] beforeCreate hooks are run but not saved

### ISSUE THREAD

**Issue by danwdart** [dadi/api#455]
I think it needs a `doc = result` or a `documents[docIndex] = result` somewhere around here otherwise it seems like it's chucking out the result it made in the beforeCreate.

Could someone verify please?

https://github.com/dadi/api/blob/370e6a80a1a54c53b8cd0c78bc66edd0811e7a06/dadi/lib/model/index.js#L249

To reproduce:

- Install API 2.3
- add a beforeCreate hook that does something trivial
- create a doc through API
- note hook does not get called

**Comment by eduardoboucas** [comment]
Are you able to replicate this in API 3.x? I could not. Here's what I'm using:

*Collection schema*

```json
{
  "fields": {
    "name": {
      "type": "String"
    }
  },
  "settings": {
    "hooks": {
      "beforeCreate": ["hook2"]
    }
  }
}
```

*workspace/hooks/hook2.js*

```js
module.exports = (obj, type, data) => {
  console.log('Hello from hook')

  obj.name = 'Modified by hook'

  return obj
}
```

When a document is created, the `console.log` fires and the document is modified as expected.

**Comment by danwdart** [comment]
I know that hooks are working fine in 3.x, it's 2.3 that's bothering me at the moment.

**Comment by danwdart** [comment]
This turned out to be a dodgy hook, which was cloning, which caused the issue. This should be fixed in 3.x anyway, by way of the hook warning.
