### ISSUE TITLE
Slug not getting generated for each Collections 

### ISSUE THREAD

**Issue by miraj92** [dadi/api#457]
### Expected behavior
Slugs should be there when we generate collections.

### Actual behaviour
After Upgrading API to 4.0, The collections in 4.0 are not generating slugs for each collection.
When we hit `/api/collections` in Dadi API v3.2, In the response we are getting Slug key as mentioned below
```
{
    "collections": [
        {
            "version": "1.0",
            "database": "tdw-api",
            "name": "About",
            "slug": "about",
            "path": "/1.0/tdw-api/about"
        }
     ]
}
```

Where in Dadi API 4.0, the Slug key is missing  Due to which https://github.com/dadi/publish/blob/develop/app/lib/models/collection.js#L43 going undefined and nothing works for publish.

### Steps to reproduce the problem
Upgrade API to 4.0 and try to access the publish

### Package details
Dadi API 
[*] 4.0

**Comment by eduardoboucas** [comment]
This should now be fixed in version 4.0.1.
