### ISSUE TITLE
Conditional batch delete

### ISSUE THREAD

**Issue by mingard** [dadi/api#46]
### Expected behavior

Requirement for a batch delete method, with suggested format of:

`http://domain.com/1.0/databse/collection?where={"title": "Duplicate article title"}`
or regex
`http://domain.com/1.0/databse/collection?where={"title": {"$regex": "/pattern/"}}`
or multiple match
`http://domain.com/1.0/databse/collection?where={"title": {"$regex": "/pattern/"}, "pages": {"$lte": 5}}`

**Comment by mingard** [comment]
A nice extension to this feature would be the ability add an optional `confirm=true` param that returns an aggregate query ObjectId for a temporary result db allowing _web_ to confirm the action with listed results before finally hitting the same uri but with an appended `deleteKey=xxxx`. 

This method provides the equivalent of a lock operation which would otherwise be a risk if there is a significant timelapse between an initial query to list potential batch delete results and the delete itself.

**Comment by eduardoboucas** [comment]
I would suggest the query for the batch delete to be included in the request body for consistency with the batch update method introduced in #48.

As for the extension you suggested (which is definitely useful), is this something we want to handle in API? It's doable, but the implementation may come with some challenges and I wonder if the complexity pays off.

Couldn't Web (or whoever is interacting with API) manage this by first sending a `GET` request with a query, which would return all the documents affected at that specific point in time, and subsequently send a `DELETE` request with a query containing all the documents IDs to be deleted?

This would effectively mean the client would create its own lock with the `GET`, whilst allowing API to still batch delete documents directly without requiring confirmation (and two requests), keeping it simple, in line with basic REST and existing functionality.

A penny for your thoughts, @mingard and @jimlambie.

**Comment by mingard** [comment]
@eduardoboucas 

> the query for the batch delete to be included in the request body for consistency
Yes

> Couldn't Web (or whoever is interacting with API) manage this by first sending a GET request with a query
Yes

**Comment by eduardoboucas** [comment]
Yes! 🎉
