### ISSUE TITLE
Make ACL models accessible

### ISSUE THREAD

**Issue by jimlambie** [dadi/api#465]
in the same way as standard collections are accessible via the Model export, bring able to interact with the ACL models is highly desirable. 

Use case 1: querying the ACL from a custom endpoint or hook

**Comment by eduardoboucas** [comment]
Let's get this in 4.1!

**Comment by eduardoboucas** [comment]
The API needs to be documented before we release.

**Comment by eduardoboucas** [comment]
This was added in 4.1.1. Still needs docs, though. 😱

**Comment by eduardoboucas** [comment]
🎁 https://docs.dadi.cloud/api/4.1#using-models-directly
