### ISSUE TITLE
Ability to filter stats endpoint

### ISSUE THREAD

**Issue by mingard** [dadi/api#47]
### Expected behavior

Either by using the existing `/stats/` endpoint or an additional `/meta` endpoint, give the ability to get meta-like detail with filters e.g.
`http://host.com:80/1.0/db/collection/metadata?filter={"answer": "yes"}`

### Expected response

```JSON
{ "metadata": {
    "limit": 40,
    "totalCount": 434,
    "totalPages": 11
  }
}
```

**Comment by jimlambie** [comment]
Closed by d71cc4cd288eb46348a7bd7735ae827d53a83efe

**Comment by mingard** [comment]
@dark12222000 the `/count` endpoint doesn't return the correct response

**Comment by jimlambie** [comment]
Looks like its getting the limit from the collection schema - `limit` should be removed from the `options` object before calling `find()`

**Comment by mingard** [comment]
Thought it would be something simple
