### ISSUE TITLE
Configurable use of body-parser middleware

### ISSUE THREAD

**Issue by abovedave** [dadi/api#489]
Unless I'm missing something it's currently it's not possible to access the raw `req.body` data as everything is processed by the `body-parser` middleware in custom endpoints.

Ideally there would be an option to turn it off or at least have access to the raw buffer via `req.rawBody` or similar.

**Comment by jimlambie** [comment]
@abovedave if you put more info re the use case and what you're trying to do, we'll be able to construct a test for it.
