### ISSUE TITLE
Search results are not composed

### ISSUE THREAD

**Issue by abovedave** [dadi/api#496]
### Expected behavior

Referenced documents to be resolved in a collection search endpoint.

### Actual behavior

Documents are not fully resolved

### Steps to reproduce the problem

I have a searchable faq datasource that links questions to a parent article.

```json
{
  "datasource": {
    "key": "faq",
    "source": {
      "endpoint": "1.0/cloud/faq/search?q={q}"
    },
    "count": 24,
    "paginate": true,
    "sort": {
      "_createdAt": -1
    },
    "requestParams": [
      {
        "source": "request",
        "param": "query",
        "field": "q",
        "target": "endpoint"
      }
    ]
  }
} 
```

### Package details

DADI API 4.3.0

**Comment by jimlambie** [comment]
Unable to reproduce using either the Web datasource as above or with a REST client. Please reopen if this continues to be a problem.
