### ISSUE TITLE
Generate and store hashes for images

### ISSUE THREAD

**Issue by anaumovets** [dadi/api#497]
When using Publish, uploading images from device is a standard operation. This can result in a lot of duplicate images if we don't do the check. So the solution is to store image hash as one of the image document fields. The hash function must be chosen so as to eliminate the risk of different images having the same hash.

**Comment by anaumovets** [comment]
As we're looking for a function that will give different hashes for even slightly different images, cryptographic hashes such as sha-2 seem to be the best choice. Additional 32 bytes (sha-256) per image shouldn't be noticeable in terms of space, and will guarantee that there are no collisions even if one tries hard. Still filenames should be either checked or added to the data when calculating hash, because I suppose identical files with different names should be allowed.

**Comment by eduardoboucas** [comment]
I don't think this is something API should do. It should simply handle uploads and not be prescriptive about what is uploaded vs. what it already holds. If people want to upload the same image 1,000 times, it's their problem and they might have a perfectly valid reason for doing so.

Closing.
