### ISSUE TITLE
Schema validation is enforced on all sub-elements of a Mixed fields

### ISSUE THREAD

**Issue by fra967** [dadi/api#51]
### Expected behaviour

Anything can be stored in a Mixed field (similarly to an Object field)

(I may be missing something here, is there any specific difference between a Mixed and an Object field?)

### Actual behaviour

All sub-elements of a Mixed field are checked against the schema, like they were at root level

### Steps to reproduce the problem

Store a structured element in a Mixed field; operation fails

`[Error: Model Validation Failed]\n  statusCode: 400,\n  json: { success: false, errors: [ [Object] ] } }`

### Package details

API 1.4.0

**Comment by jimlambie** [comment]
@fra967 that's a badly stringifed error message - is that from a log file or the console?

**Comment by fra967** [comment]
thank you Jim, that error appeared in the console
