### ISSUE TITLE
Add `runHooks` parameter to model methods

### ISSUE THREAD

**Issue by eduardoboucas** [dadi/api#512]
Currently, any configured hooks will always run as part of create, update and delete operations. Whilst this is expected for requests to the RESTful endpoints, it's not always desirable to have hooks running as part of calls to the model methods, as it can lead to hooks triggering other hooks in unexpected ways, potentially leading to infinite loops. This was reported in #258.

If we introduce a `runHooks` parameter to `model.create`, `model.delete`, `model.get` and `model.update`, we can bypass hook execution when needed. What I'm not sure about is what the default value for this new parameter should be.

On the one hand, it makes sense to make it `true`. This is fully backwards-compatible, as no changes are required to retain the current functionality. Sending `{runHooks: false}` to the model methods would change the default behaviour and stop hooks from running.

On the other hand, we could default to `false` and change the controller methods to include `{runHooks: true}` in their own calls to the model methods. In practice, this means that requests made to the RESTful endpoints will continue to work in the same way, as it's not possible for end users to bypass hooks (and it shouldn't be, for security reasons), but any calls to the model methods would need to *actively enable* hooks.

**Pros of option 1**: Maintains backwards-compatibility
**Pros of option 2**: Solves #258 in itself

Thoughts @mingard @jimlambie?

**Comment by mingard** [comment]
Of the two I would favour option 1. The current default behaviour makes sense, and under most circumstances running hooks is fine.

Ideally, at least for my experience with the issue, a flag for the source of the call would be great. Some type of _internal/external_ parameter.

To extend this to solve #258, perhaps introducing some way of attaching data to the calls from within the hook would be a more generalised feature to help understand more about the call. Being able to set `callCounter` on a metadata parameter that can be received by the Model.

```js
calledByBeforeCreate ++
await Model('foo').somePassthroughMethod({calledByBeforeCreate})
  .update({
    query: {
      title: 'Bacon Bites'
    },
    update: {
      deliciousRating:  5.0
    }
  })
```

**Comment by jimlambie** [comment]
@eduardoboucas sorry I havent had a chance to review this. Will do so ASAP
