### ISSUE TITLE
"False" filter on Boolean field 

### ISSUE THREAD

**Issue by jimlambie** [dadi/api#539]
When filtering documents using a Boolean field, API only returns results where the field is explicitly set to either "true" or "false". 

This means that filtering on "false" will not return documents where the field hasn't been set at all, or rather, doesn't exist.

In the following example dataset:
1. `{"published": true}` returns `["Article 1"]`
2. `{"published": false}` returns `["Article 2"]`

```
[
  {
    "title": "Article 1",
    "published": true
  }
  {
    "title": "Article 2",
    "published": false
  }
  {
    "title": "Article 3"
  }
]

```

We propose that any "field is false" query on a Boolean field is modified to become a "field is not equal to true" query:

* original: `{"published": false}`
* modified: `{"published": {"$ne": true}}`

This modification changes the behaviour so that using the above example dataset, we'd get:
2. `{"published": false}` returns `["Article 2", "Article 3"]`

**Comment by adamkdean** [comment]
> We propose that any "field is false" query on a Boolean field is modified to become a "field is not equal to true" query

I agree. By being undefined, `publishes` is essentially falsey.
