### ISSUE TITLE
Publish fields as standard

### ISSUE THREAD

**Issue by mingard** [dadi/api#55]
### Expected behavior

Bake in publish state, date, expires date, publisher as standard.

**Comment by jimlambie** [comment]
@josephdenne more info required please. 

* publishState: ok
* publishDate: ok
* publishEndDate: ok
* publisher: what is this? is it a string supplied by the publishing system? or an editor identifier?

**Comment by mingard** [comment]
@jimlambie confirming that Publisher means editor

**Comment by eduardoboucas** [comment]
@jimlambie Do you want help with this one? Feel free to assign to me.

**Comment by mingard** [comment]
@eduardoboucas @jimlambie @josephdenne I believe with the introduction of `collection type` and Publish `collection` recipes (marketplace) this is no longer a strict requirement.

**Comment by eduardoboucas** [comment]
I'm very happy with that, as it separates concerns and keeps API agnostic of implementation. 

Closing! 🍷
