### ISSUE TITLE
Delete old records from history collections

### ISSUE THREAD

**Issue by fra967** [dadi/api#65]
History collections are growing indefinitely and creating un-necessary load, both in terms of write operations and storage.
As they are not accessible out of the API layer, we need a command-line tool shipped with API to perform regular clean up, such as extract a copy of all historical records older than a certain amount of time and delete them from the MongoDB collections.

Configurable parameters:
- timestamp to identify records to be deleted
- wether to extract a copy of the old records or simply delete them

**Comment by jimlambie** [comment]
https://github.com/dadi/toolbelt
