### ISSUE TITLE
Tokens expiring prematurely

### ISSUE THREAD

**Issue by eduardoboucas** [dadi/api#75]
### Expected behavior

Bearer tokens should be invalidated according to the `auth.tokenTtl` value set in config.

### Actual behavior

Tokens are being invalidated before the supposed expiry date.

### Steps to reproduce the problem

Set `auth.tokenTtl` to a large value (e.g. `86400`), request a bearer token and try to use it after a few hours.

### Package details

API v1.6.4

**Comment by jimlambie** [comment]
This will be due to the Mongo ttl index being created the first time api is run. It won't be reconfigured following a config change, so the original ttl value will be used.

**Comment by jimlambie** [comment]
https://github.com/dadi/api/blob/master/dadi/lib/auth/tokenStore.js#L42-L53

I believe the `expire` method can be removed, and within the constructor we can drop and recreate indexes for the token collection - this should only occur each time the API is restarted, and the token collection isn't terribly large (currently)

**Comment by jimlambie** [comment]
Startup logging now reports:

```
[2016-05-10 16:01:40.899] [LOG]   Dropped authentication layer indexes
[2016-05-10 16:01:40.902] [LOG]   Created token expiry index "tokenStore.created_1', with expireAfterSeconds = 1800
[2016-05-10 16:01:40.903] [LOG]   Created token index "tokenStore.token_1_tokenExpire_1'
```
