### ISSUE TITLE
NPM registry check: uncaught 500

### ISSUE THREAD

**Issue by mingard** [dadi/api#92]
### Expected behavior

NPM registry check failure to be caught

### Actual behavior

App crash and error:

```JSON
{
  "message": "Response code 500 (Internal Server Error)",
  "host": "registry.npmjs.org",
  "hostname": "registry.npmjs.org",
  "method": "GET",
  "path": "/@dadi%2Fapi",
  "statusCode": 500,
  "statusMessage": "Internal Server Error"
}
```

### Steps to reproduce the problem

Repeat calls to the status api endpoint

**Comment by eduardoboucas** [comment]
I've been bombarding my status endpoint and I haven't been able to replicate this. Is this still an issue, and if so could you help me replicate? Access to the instance would help.

Thanks! 👊

**Comment by jimlambie** [comment]
Please reopen if this becomes an issue again, thanks.

**Comment by mingard** [comment]
I can't replicate either - thanks

**Comment by fra967** [comment]
I had a similar issue while connected on a very slow mobile connection, and i could trace a call to `registry.npmjs.org/@dadi%2Fapi`
When is this call happening? and is it necessary?

**Comment by jimlambie** [comment]
Resolved by
https://github.com/dadi/status/commit/4a61a8845b9e1939002343220ba9d8f9763bfc27
and the latest NPM version of @dadi/status
