### ISSUE TITLE
Article History

### ISSUE THREAD

**Issue by mingard** [dadi/api#93]
- [x] Introduce `/{version}/{db}/{collection}?history=true`
- [x] Return all historic versions including current
- [ ] Allow `?fields` param to continue to define which fields to return
- [ ] Date range filtering

Further concepts
- Filter where fields have changed e.g. `?whereChange=['title', 'heroImage', 'content']`

**Comment by jimlambie** [comment]
Where fields have changed is not something we can do yet, as we currently only store the entire document and not a diff or an operation log

**Comment by jimlambie** [comment]
First two tasks done, available in 1.8.2 👷
